name: Run Python Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
    API_ID: ${{ secrets.API_ID }}
    API_HASH: ${{ secrets.API_HASH }}
    BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name : Setup Python
        uses : actions/setup-python@v4
        with :
          python-version: 3.10.6

      - name: Run python script
        run: |
            pip install pyrogram
            python3 main.py
